// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtQGyfqX_zsnHu_SWVsM_-dpTb2nyeOAE',
    appId: '1:580542545691:web:590fdac27843a482609dbe',
    messagingSenderId: '580542545691',
    projectId: 'testtask-11338',
    authDomain: 'testtask-11338.firebaseapp.com',
    storageBucket: 'testtask-11338.appspot.com',
    measurementId: 'G-T35342QCQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIj5t6ymX6HdoqAlQzjzwxGa-0M2N9Hyk',
    appId: '1:580542545691:android:12de8feca0219e16609dbe',
    messagingSenderId: '580542545691',
    projectId: 'testtask-11338',
    storageBucket: 'testtask-11338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtzJTY5s9lPrUhdg9kSx880HD2vsyOvTQ',
    appId: '1:580542545691:ios:18c43002cd9e7fe2609dbe',
    messagingSenderId: '580542545691',
    projectId: 'testtask-11338',
    storageBucket: 'testtask-11338.appspot.com',
    iosBundleId: 'com.example.testtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtzJTY5s9lPrUhdg9kSx880HD2vsyOvTQ',
    appId: '1:580542545691:ios:18c43002cd9e7fe2609dbe',
    messagingSenderId: '580542545691',
    projectId: 'testtask-11338',
    storageBucket: 'testtask-11338.appspot.com',
    iosBundleId: 'com.example.testtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtQGyfqX_zsnHu_SWVsM_-dpTb2nyeOAE',
    appId: '1:580542545691:web:7feb7838579977af609dbe',
    messagingSenderId: '580542545691',
    projectId: 'testtask-11338',
    authDomain: 'testtask-11338.firebaseapp.com',
    storageBucket: 'testtask-11338.appspot.com',
    measurementId: 'G-Q8X2EK1EKY',
  );

}