// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Qj-G2shZ8u4z6cy3RfdKC0imT68h1w4',
    appId: '1:703960613308:web:f0f1bafc8300b26988abb9',
    messagingSenderId: '703960613308',
    projectId: 'notify-task-a7e06',
    authDomain: 'notify-task-a7e06.firebaseapp.com',
    storageBucket: 'notify-task-a7e06.appspot.com',
    measurementId: 'G-KVGR3RQHFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyyFr3Z96MjskS0BobeDYInS5WK8fTkZc',
    appId: '1:703960613308:android:0db09706f9f6ab7188abb9',
    messagingSenderId: '703960613308',
    projectId: 'notify-task-a7e06',
    storageBucket: 'notify-task-a7e06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdOADZ3RgP_b0AB5E6A2TpcCuWuDQPz7E',
    appId: '1:703960613308:ios:f19c5cb05ecbfbc488abb9',
    messagingSenderId: '703960613308',
    projectId: 'notify-task-a7e06',
    storageBucket: 'notify-task-a7e06.appspot.com',
    iosBundleId: 'com.example.notifyTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdOADZ3RgP_b0AB5E6A2TpcCuWuDQPz7E',
    appId: '1:703960613308:ios:f19c5cb05ecbfbc488abb9',
    messagingSenderId: '703960613308',
    projectId: 'notify-task-a7e06',
    storageBucket: 'notify-task-a7e06.appspot.com',
    iosBundleId: 'com.example.notifyTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Qj-G2shZ8u4z6cy3RfdKC0imT68h1w4',
    appId: '1:703960613308:web:26fdf715d7e2394a88abb9',
    messagingSenderId: '703960613308',
    projectId: 'notify-task-a7e06',
    authDomain: 'notify-task-a7e06.firebaseapp.com',
    storageBucket: 'notify-task-a7e06.appspot.com',
    measurementId: 'G-LN62CVGK7T',
  );
}
